### ISSUE TITLE
How to Uninstall the plugin ?

### ISSUE THREAD

**Issue by srugano** [fossfreedom/radio-browser#11]
I have installed the plugin, but it doesn't work. How can I uninstall it ? When I clic to enable it, it says that Plugin "Internet radio station browser" 
An error occured : Plugin loader "python" wasn't found

**Comment by fossfreedom** [comment]
if you have installed this locally then remove the folder under ~/.local/share/rhythmbox/plugins

Please read the README - it makes it clear - if you are installing the plugin for RB3 and later you need to install the software located in the RB3 branch - not the master branch which (again) the README states is for versions before RB3
